name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Playwright Docker image
      run: docker pull andreybitkov/playwright-tests:latest

    - name: Run Smoke Tests
      if: github.event_name == 'push'
      run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results -w /app andreybitkov/playwright-tests:latest npx playwright test --grep @smoke --reporter=allure-playwright

    - name: Run Regression Tests
      if: github.event_name == 'pull_request'
      run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results -w /app andreybitkov/playwright-tests:latest npx playwright test --grep @regression --reporter=allure-playwright

    - name: Run API Tests
      run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results -w /app andreybitkov/playwright-tests:latest npx playwright test --grep @api --reporter=allure-playwright

    - name: Generate Allure Report using Allure Docker image
      run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results -v ${{ github.workspace }}/allure-report:/app/allure-report frankescobar/allure-docker-service sh -c "allure generate /app/allure-report/ -o /app/allure-report/ --clean"
    
    
    - name: Upload Allure Report as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: /app/allure-report/
    
