name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Playwright Docker image
        run: docker pull andreybitkov/playwright-tests:latest

      - name: Install Playwright Dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app andreybitkov/playwright-tests:latest \
            sh -c "npm install && npx playwright install --with-deps"

      - name: Run Smoke Tests
        if: github.event_name == 'push'
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -w /app andreybitkov/playwright-tests:latest \
            sh -c "npm install && npx playwright test --grep @smoke --reporter=html"

      - name: Run Regression Tests
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm \
           -v ${{ github.workspace }}:/app \
           -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
           -w /app andreybitkov/playwright-tests:latest \
           sh -c "npm install && npx playwright test --grep @regression --reporter=html"

  
      - name: Upload Playwright Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/**
