name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies and Playwright with Allure
      run: |
        npm install
        npm install --save-dev @playwright/test allure-playwright allure-commandline
        npx playwright install --with-deps

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-deps-

  test:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Restore node modules and Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache/ms-playwright
        key: ${{ needs.setup.outputs.cache-key }}

    - name: Run smoke tests
      if: github.event_name == 'push'
      run: npm run test:smoke

    - name: Run regression tests
      if: github.event_name == 'pull_request'
      run: npm run test:all

    - name: Generate Allure report
      run: npx allure generate allure-results --clean

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v4
      with:
        n
