name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Playwright Docker image
      run: docker pull andreybitkov/playwright-tests:latest

    - name: Run smoke tests
      if: github.event_name == 'push'
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app andreybitkov/playwright-tests:latest npm run test:smoke

    - name: Run regression tests
      if: github.event_name == 'pull_request'
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app andreybitkov/playwright-tests:latest npm run test:all

    - name: Run API tests
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app andreybitkov/playwright-tests:latest npm run test:api

    - name: Generate Allure report
      run: docker run --rm -v ${{ github.workspace }}:/app -w /app andreybitkov/playwright-tests:latest npx allure generate allure-results --clean

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
