name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest Playwright Docker image
        run: docker pull andreybitkov/playwright-tests:latest

      # Отладка: Проверяем файлы перед запуском тестов
      - name: Debug Files in CI/CD
        run: ls -la ${{ github.workspace }}

      # Запуск Smoke Tests через `npm run test:smoke`
      - name: Run Smoke Tests
        if: github.event_name == 'push'
        run: |
          docker run --rm \
            --platform linux/amd64 \
            -v ${{ github.workspace }}:/app \
            -w /app andreybitkov/playwright-tests:latest \
            sh -c "npm run test:smoke"

      # Запуск Regression Tests через `npm run test:all`
      - name: Run Regression Tests
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm \
            --platform linux/amd64 \
            -v ${{ github.workspace }}:/app \
            -w /app andreybitkov/playwright-tests:latest \
            sh -c "npm run test:all"

      # Запуск API Tests через `npm run test:api`
      - name: Run API Tests
        run: |
          docker run --rm \
            --platform linux/amd64 \
            -v ${{ github.workspace }}:/app \
            -w /app andreybitkov/playwright-tests:latest \
            sh -c "npm run test:api"

      # Отладка: Проверяем, есть ли HTML-репорт перед загрузкой
      - name: Debug Playwright Report Files
        run: ls -la ${{ github.workspace }}/playwright-report || echo "No report found!"

      # Загружаем HTML-отчет Playwright в артефакты CI/CD
      - name: Upload Playwright Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/**
