name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Playwright Docker image
      run: docker pull andreybitkov/playwright-tests:latest

    - name: Run Smoke Tests
      if: github.event_name == 'push'
      run: docker run --rm -v ${{ github.workspace }}:/app -v /app/node_modules -w /app andreybitkov/playwright-tests:latest --grep @smoke

    - name: Run Regression Tests
      if: github.event_name == 'pull_request'
      run: docker run --rm -v ${{ github.workspace }}:/app -v /app/node_modules -w /app andreybitkov/playwright-tests:latest --grep @regression

    - name: Run API Tests
      if: github.event_name == 'pull_request'
      run: docker run --rm -v ${{ github.workspace }}:/app -v /app/node_modules -w /app andreybitkov/playwright-tests:latest --grep @api

    - name: Generate Allure Report
      run: docker run --rm -v ${{ github.workspace }}:/app -v /app/node_modules -w /app andreybitkov/playwright-tests:latest npx allure generate allure-results --clean

    - name: Upload Allure Report as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
