name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Playwright Docker image
      run: docker pull andreybitkov/playwright-tests:latest

    - name: Run Smoke Tests
      if: github.event_name == 'push'
      run: docker run --rm -v ${{ github.workspace }}:/app -v /app/node_modules -w /app andreybitkov/playwright-tests:latest --grep @smoke

    - name: Run Regression Tests
      if: github.event_name == 'pull_request'
      run: docker run --rm -v ${{ github.workspace }}:/app -v /app/node_modules -w /app andreybitkov/playwright-tests:latest --grep @regression

    - name: Run API Tests
      run: docker run --rm -v ${{ github.workspace }}:/app -v /app/node_modules -w /app andreybitkov/playwright-tests:latest --grep @api

    - name: Check Allure Version in CI
      run: docker run --rm andreybitkov/playwright-tests:latest allure --version
    
    - name: List files in Allure Results
      run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results andreybitkov/playwright-tests:latest ls -la /app/allure-results
      
    - name: Generate Allure Report
      run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results -v ${{ github.workspace }}/allure-report:/app/allure-report andreybitkov/playwright-tests:latest allure generate /app/allure-results /app/allure-report
    
    
    - name: Upload Allure Report as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
