name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Smoke Tests
        if: github.event_name == 'push'
        run: npm run test:smoke

      - name: Run Regression Tests
        if: github.event_name == 'pull_request'
        run: npm run test:all

      - name: Run API Tests
        run: npm run test:api

      - name: Generate Allure Report
        run: npx allure-playwright generate allure-results -o allure-report || echo "Allure report generation failed!"

      - name: Upload Allure Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/**
